### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hrdlnk** [SantiMA10/tailwindcss-parcel-starter#112]
Issue while building. Not sure what the problem is...
 
```sh
/tmp/tailwindcss-parcel-starter(master ✗) npm run dev

> tailwindcss-parcel-starter@1.0.0 dev /private/tmp/tailwindcss-parcel-starter
> parcel src/index.html

Server running at http://localhost:1234 
🚨  /private/tmp/tailwindcss-parcel-starter/src/assets/css/styles.css:undefined:undefined: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/node_modules/postcss/lib/postcss.js:55:10)
    at module.exports (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/transforms/postcss.js:17:19)
    at async CSSAsset.transform (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/assets/CSSAsset.js:133:5)
    at async CSSAsset.process (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/Asset.js:216:7)
    at async Pipeline.processAsset (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/Pipeline.js:24:23)
    at async Object.run (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (/private/tmp/tailwindcss-parcel-starter/node_modules/parcel-bundler/src/Bundler.js:577:19)
```

**Comment by SantiMA10** [comment]
Hi @hrdlnk!

You can use the PR https://github.com/SantiMA10/tailwindcss-parcel-starter/pull/115 contains the needed changes to fix the problem or you can clone the repo again.
